version: '3.8'

services:
  db:
    image: postgres:bookworm
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: district
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
